#!/usr/bin/env bash
# Write VITE_FIREBASE_* from Terraform output into web/.env.local
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
ENV_FILE="${ROOT}/web/.env.local"
API_URL="${VITE_API_URL:-https://ttf-api-6ac5e3cakq-uc.a.run.app}"

JSON="$(docker compose -f "${ROOT}/docker-compose.yml" run --rm terraform \
  -chdir=environments/dev output -json firebase_web_env)"

API_KEY="$(printf '%s' "$JSON" | python -c "import sys,json; print(json.load(sys.stdin)['VITE_FIREBASE_API_KEY'])")"
AUTH_DOMAIN="$(printf '%s' "$JSON" | python -c "import sys,json; print(json.load(sys.stdin)['VITE_FIREBASE_AUTH_DOMAIN'])")"
PROJECT_ID="$(printf '%s' "$JSON" | python -c "import sys,json; print(json.load(sys.stdin)['VITE_FIREBASE_PROJECT_ID'])")"

cat >"$ENV_FILE" <<EOF
# Generated by web/scripts/sync-env-from-terraform.sh — do not commit
VITE_FIREBASE_API_KEY=${API_KEY}
VITE_FIREBASE_AUTH_DOMAIN=${AUTH_DOMAIN}
VITE_FIREBASE_PROJECT_ID=${PROJECT_ID}
VITE_API_URL=${API_URL}
EOF

echo "Wrote ${ENV_FILE}"
