// Generated by scripts/generate-design-tokens.mjs — do not edit.

import SwiftUI
import UIKit

extension Color {
    static let brand = Color("Brand")
    static let brandHover = Color("BrandHover")
    static let brandSoft = Color("BrandSoft")
    static let accent = Color("Accent")
    static let accentPop = Color("AccentPop")
    static let accentSoft = Color("AccentSoft")
    static let bg = Color("Bg")
    static let surface = Color("Surface")
    static let surfaceRaised = Color("SurfaceRaised")
    static let surfaceMuted = Color("SurfaceMuted")
    static let border = Color("Border")
    static let borderStrong = Color("BorderStrong")
    static let text = Color("Text")
    static let textMuted = Color("TextMuted")
    static let textInverse = Color("TextInverse")
    static let error = Color("Error")
    static let errorSoft = Color("ErrorSoft")
    static let success = Color("Success")
    static let successSoft = Color("SuccessSoft")
    static let warning = Color("Warning")
    static let warningSoft = Color("WarningSoft")
    static let ttfFast = Color("TtfFast")
    static let ttfOk = Color("TtfOk")
    static let ttfSlow = Color("TtfSlow")
    static let ttfUnknown = Color("TtfUnknown")
    static let pinSearchFocus = Color("PinSearchFocus")
    static let mapLand = Color("MapLand")
    static let mapWater = Color("MapWater")
    static let mapPark = Color("MapPark")
    static let paperDot = Color("PaperDot")
}

// MARK: - Brand type (Bluebird: Quicksand display / Nunito body)
//
// Static-weight TTFs are bundled in TTF/Resources/Fonts and registered via
// UIAppFonts in Info.plist. Every helper falls back gracefully to the system
// font (rounded design for display) when a face is missing, so the app never
// crashes or renders blank text if the fonts fail to register.

extension Font {
    /// Quicksand — display, headings, big TTF numbers.
    static func lsDisplay(_ size: CGFloat, weight: Font.Weight = .semibold) -> Font {
        LSBrandFont.font(family: .display, size: size, weight: weight)
    }

    /// Nunito — UI and body copy.
    static func lsBody(_ size: CGFloat, weight: Font.Weight = .regular) -> Font {
        LSBrandFont.font(family: .body, size: size, weight: weight)
    }

    // Semantic shortcuts (Bluebird type scale, tokens/typography.css).
    /// Page titles — Quicksand 34 bold.
    static let lsLargeTitle = lsDisplay(34, weight: .bold)
    /// Section titles (h1) — Quicksand 26 bold.
    static let lsTitle = lsDisplay(26, weight: .bold)
    /// Sub-section titles (h2) — Quicksand 21 bold.
    static let lsTitle2 = lsDisplay(21, weight: .bold)
    /// Card / row headlines (h3) — Quicksand 18 semibold.
    static let lsHeadline = lsDisplay(18, weight: .semibold)
    /// Flagship TTF figure — Quicksand 38 bold.
    static let lsNumber = lsDisplay(38, weight: .bold)
    /// Body copy — Nunito 15 regular.
    static let lsBodyText = lsBody(15)
    /// Secondary copy / captions — Nunito 13 semibold.
    static let lsCaption = lsBody(13, weight: .semibold)
    /// Eyebrow labels — Nunito 11 extra-bold (track + uppercase at call site).
    static let lsLabel = lsBody(11, weight: .heavy)
}

/// Resolves bundled brand faces with graceful system fallback.
enum LSBrandFont {
    enum Family {
        case display
        case body
    }

    static let displayFamily = "Quicksand"
    static let bodyFamily = "Nunito"

    /// PostScript names of the faces actually registered at runtime.
    private static let availableFaces: Set<String> = {
        let candidates = [
            "Quicksand-Medium", "Quicksand-SemiBold", "Quicksand-Bold",
            "Nunito-Regular", "Nunito-Medium", "Nunito-SemiBold",
            "Nunito-Bold", "Nunito-ExtraBold",
        ]
        return Set(candidates.filter { UIFont(name: $0, size: 12) != nil })
    }()

    static func font(family: Family, size: CGFloat, weight: Font.Weight) -> Font {
        let name = faceName(family: family, weight: weight)
        guard availableFaces.contains(name) else {
            return .system(size: size, weight: weight, design: family == .display ? .rounded : .default)
        }
        return .custom(name, size: size)
    }

    private static func faceName(family: Family, weight: Font.Weight) -> String {
        switch family {
        case .display:
            // Bundled: Medium (500), SemiBold (600), Bold (700).
            switch weight {
            case .ultraLight, .thin, .light, .regular, .medium: return "\(displayFamily)-Medium"
            case .semibold: return "\(displayFamily)-SemiBold"
            default: return "\(displayFamily)-Bold"
            }
        case .body:
            // Bundled: Regular (400), Medium (500), SemiBold (600), Bold (700), ExtraBold (800).
            switch weight {
            case .ultraLight, .thin, .light, .regular: return "\(bodyFamily)-Regular"
            case .medium: return "\(bodyFamily)-Medium"
            case .semibold: return "\(bodyFamily)-SemiBold"
            case .bold: return "\(bodyFamily)-Bold"
            default: return "\(bodyFamily)-ExtraBold"
            }
        }
    }
}
