// Generated by scripts/generate-design-tokens.mjs — do not edit.

import SwiftUI

enum TtfTier: String, CaseIterable {
    case fast
    case ok
    case slow
    case unknown

    var label: String {
        switch self {
        case .fast: "Fast (≤8 min)"
        case .ok: "OK (9–15 min)"
        case .slow: "Slow (>15 min)"
        case .unknown: "Not enough data"
        }
    }

    var color: Color {
        switch self {
        case .fast: .ttfFast
        case .ok: .ttfOk
        case .slow: .ttfSlow
        case .unknown: .ttfUnknown
        }
    }
}

enum TtfTierLogic {
    static func tier(for ttf: TtfAggregate) -> TtfTier {
        guard ttf.sampleSize >= 3, let median = ttf.medianMinutes else {
            return .unknown
        }
        if median <= 8 { return .fast }
        if median <= 15 { return .ok }
        return .slow
    }

    static func formattedMedian(_ ttf: TtfAggregate) -> String {
        guard ttf.sampleSize > 0, let median = ttf.medianMinutes else {
            return "—"
        }
        return "\(Int(median.rounded())) min"
    }
}
